version: '3.4'
services:
  jira:
    image: haxqer/jira:9.17.0
    container_name: jira-srv
    environment:
      - VIRTUAL_HOST=test.com # CHANGE THIS TO YOUR DOMAIN
#      - JVM_MINIMUM_MEMORY=1g
#      - JVM_MAXIMUM_MEMORY=12g
#      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - postgresql
    # ports:
    #   - "8080:8080"
    volumes:
      - home_data:/var/jira
    restart: always
    networks:
      - network-bridge
      
  # nginx-letsencrypt:
  #   container_name: nginx-letsencrypt
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   restart: always
  #   environment:
  #     NGINX_PROXY_CONTAINER: nginx-proxy
  #     NGINX_DOCKER_GEN_CONTAINER: nginx-gen
  #   volumes_from:
  #     - nginx-proxy
  #   volumes:
  #     - ./configs/nginx/certs:/etc/nginx/certs:rw
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   networks:
  #     - network-bridge

  confluence:
    image: haxqer/confluence:8.9.4
    container_name: confluence-srv
    environment:
      - VIRTUAL_HOST=conf.test.com # CHANGE THIS TO YOUR DOMAIN
    #      - JVM_MINIMUM_MEMORY=1g
    #      - JVM_MAXIMUM_MEMORY=12g
    #      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - postgresql
    # ports:
    #   - "8090:8090"
    volumes:
      - home_data:/var/confluence
    restart: always
    networks:
      - network-bridge
  
  postgresql:
    restart: always
    image: postgres:15
    container_name: psql-jira
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - network-bridge
  
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./configs/nginx/vhost.d:/etc/nginx/vhost.d
      - ./configs/nginx/html:/usr/share/nginx/html
      - ./configs/nginx/certs:/etc/nginx/certs:ro
    networks:
      - network-bridge

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    restart: always
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./configs/nginx-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
  postgresql_data:
    external: false
